export const UPDATE_CURRENT_MENU_ITEM_ACTIVE 	= 'updateCurrentMenuItemActive'
export const UPDATE_SHOW_PANEL 								= 'updateShowPanel'
export const SET_LOGO_HEADER 									= 'setLogoHeader'
export const SET_MAIN_COLOR 									= 'setMainColor'
export const SET_MAIN_COLOR_DARK 							= 'setMainColorDark'
export const SET_MAIN_COLOR_LIGHT 						= 'setMainColorLight'
export const SET_SECOND_COLOR 								= 'setSecondColor'
export const SET_MENU_ITEMS 									= 'setMenuItems'
